### ISSUE TITLE
Fix gemnasium

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-layout#21]
Gemnasium badge on the repo is broken for some reason.
https://gemnasium.com/cfpb/cf-layout

**Comment by KimberlyMunoz** [comment]
Gemnasium doesn't have access to CFPB repos. We'll have to remove the badge.

**Comment by Scotchester** [comment]
It has access to some; cf-layout never got enabled because it wasn't part of the first wave of components.

The question is, do we find it of value enough to keep using? And in potential single-repo world, it probably won't be useful, anyway.

**Comment by KimberlyMunoz** [comment]
I've gone and removed it in #24. I don't think it provides much value right now, but hopefully in a bright and shiny one-repo future we can bring it back. 🌈
